#!/bin/bash
set -e

PROJECT_ROOT="/path/to/traj_opt_paper"
LAUNCHER="$PROJECT_ROOT/final_scripts/traj_opt.sh"

# SiT-S --------- using finetuned flownet as starting point
SIT_MODEL="SiT-S/2"
PATH_BETA=0.95
NUM_CYCLES=3
FLOW_EMA_DECAY="0"
OUT_ROOT="$PROJECT_ROOT/output/final_repro/SiT-S-2"
INITIAL_FLOW_CKPT="finetuned_ckpt/sit-s-2_initial.pt"
PATH_TEACHER_CKPT="finetuned_ckpt/sit-s-2_initial.pt"
GEN_CONFIG_PATH="$PROJECT_ROOT/gen_configs/SiT-S-2_cfg3.5.sh"
PATH_PER_GPU_BATCH_SIZE=280  # default 280
FLOW_PER_GPU_BATCH_SIZE=768  # default 768




PATH_MODEL="${PATH_MODEL:-SiT-S/2}"
INITIAL_PATH_CKPT="$PROJECT_ROOT/checkpoints/SiT-S-2-256_orig.pt"
PATH_STAGE_STEPS="${PATH_STAGE_STEPS:-3000}"
PATH_LR_ANNEAL_STEPS="${PATH_LR_ANNEAL_STEPS:-$PATH_STAGE_STEPS}"
PATH_CKPT_EVERY="${PATH_CKPT_EVERY:-$PATH_STAGE_STEPS}"
PATH_EVAL_EVERY="${PATH_EVAL_EVERY:-$PATH_STAGE_STEPS}"
FLOW_STAGE_STEPS="${FLOW_STAGE_STEPS:-4000}"

mkdir -p "$PROJECT_ROOT/logs" "$PROJECT_ROOT/output"
cd "$PROJECT_ROOT"

echo "OUT_ROOT=$OUT_ROOT"
echo "SIT_MODEL=$SIT_MODEL"
echo "PATH_MODEL=$PATH_MODEL"
echo "GEN_CONFIG_PATH=$GEN_CONFIG_PATH"
echo "INITIAL_FLOW_CKPT=$INITIAL_FLOW_CKPT"
echo "INITIAL_PATH_CKPT=$INITIAL_PATH_CKPT"
echo "PATH_TEACHER_CKPT=$PATH_TEACHER_CKPT"
echo "FLOW_EMA_DECAY=$FLOW_EMA_DECAY"
echo "PATH_BETA=$PATH_BETA"
echo "NUM_CYCLES=$NUM_CYCLES"
echo "PATH_STAGE_STEPS=$PATH_STAGE_STEPS"
echo "PATH_LR_ANNEAL_STEPS=$PATH_LR_ANNEAL_STEPS"
echo "PATH_CKPT_EVERY=$PATH_CKPT_EVERY"
echo "PATH_EVAL_EVERY=$PATH_EVAL_EVERY"
echo "X0_HAT_RHO_SCALE=$X0_HAT_RHO_SCALE"
echo "FLOW_STAGE_STEPS=$FLOW_STAGE_STEPS"
echo "RESUME_FROM_CYCLE_DIR=${RESUME_FROM_CYCLE_DIR:-<none>}"

# 
NPROC_PER_NODE=1 \
OUT_ROOT="$OUT_ROOT" \
SIT_MODEL="$SIT_MODEL" \
PATH_MODEL="$PATH_MODEL" \
GEN_CONFIG_PATH="$GEN_CONFIG_PATH" \
ATTN_FUNC="fa3" \
AMP_DTYPE="bf16" \
NUM_CYCLES="$NUM_CYCLES" \
SKIP_PATH_STAGE_CYCLE1=0 \
INITIAL_FLOW_CKPT="$INITIAL_FLOW_CKPT" \
INITIAL_PATH_CKPT="$INITIAL_PATH_CKPT" \
PATH_TEACHER_CKPT="$PATH_TEACHER_CKPT" \
RESUME_FROM_CYCLE_DIR="$RESUME_FROM_CYCLE_DIR" \
PATH_ARCH=dual_stem_teacher_residual \
PATH_USE_ENDPOINT_CONDITIONING=1 \
PATH_LOSS_MODE=track_mixed_euclid_learned \
PATH_BETA=$PATH_BETA \
PATH_LEARNED_PATH_MIX=0.4 \
PATH_PER_GPU_BATCH_SIZE=$PATH_PER_GPU_BATCH_SIZE \
FLOW_LEARNED_PATH_MIX=0.4 \
FLOW_PER_GPU_BATCH_SIZE=$FLOW_PER_GPU_BATCH_SIZE \
FLOW_EMA_DECAY="$FLOW_EMA_DECAY" \
PATH_STAGE_STEPS="$PATH_STAGE_STEPS" \
PATH_LR_ANNEAL_STEPS="$PATH_LR_ANNEAL_STEPS" \
FLOW_STAGE_STEPS="$FLOW_STAGE_STEPS" \
PATH_AUTOSAVE_EVERY=200 \
FLOW_AUTOSAVE_EVERY=200 \
FLOW_CKPT_EVERY=2000 \
PATH_CKPT_EVERY="$PATH_CKPT_EVERY" \
PATH_EVAL_EVERY="$PATH_EVAL_EVERY" \
X0_HAT_RHO_SCALE="$X0_HAT_RHO_SCALE" \
sbatch "$LAUNCHER"
