#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
LAUNCHER="$PROJECT_ROOT/final_scripts/traj_opt.sh"
MG_CKPT="${MG_CKPT:-}"

if [[ -z "$MG_CKPT" ]]; then
  echo "Set MG_CKPT to a SiT-B/2 checkpoint trained with Model Guidance." >&2
  exit 1
fi
if [[ ! -f "$MG_CKPT" ]]; then
  echo "MG checkpoint not found: $MG_CKPT" >&2
  exit 1
fi

mkdir -p "$PROJECT_ROOT/logs" "$PROJECT_ROOT/output"
cd "$PROJECT_ROOT"

# Historical B-MG result configuration: fixed rho=0.5, two H200 workers,
# B/2 path initialized from the same 65k MG checkpoint, and real EMA=0.999.
NPROC_PER_NODE="${NPROC_PER_NODE:-2}" \
OUT_ROOT="${OUT_ROOT:-$PROJECT_ROOT/output/final_repro/SiT-B-2-MG}" \
SIT_MODEL="SiT-B/2" \
PATH_MODEL="SiT-B/2" \
GEN_CONFIG_PATH="$PROJECT_ROOT/gen_configs/SiT-B-2_mg.sh" \
MODE="ODE" \
SAMPLING_METHOD="heun2" \
NUM_SAMPLING_NFE="250" \
ATTN_FUNC="${ATTN_FUNC:-fa3}" \
AMP_DTYPE="${AMP_DTYPE:-bf16}" \
NUM_CYCLES="${NUM_CYCLES:-3}" \
NUM_FID_SAMPLES="${NUM_FID_SAMPLES:-10000}" \
INITIAL_FLOW_CKPT="$MG_CKPT" \
INITIAL_PATH_CKPT="$MG_CKPT" \
PATH_TEACHER_CKPT="$MG_CKPT" \
PATH_ARCH="${PATH_ARCH:-dual_stem_teacher_residual}" \
PATH_USE_ENDPOINT_CONDITIONING="${PATH_USE_ENDPOINT_CONDITIONING:-1}" \
PATH_LOSS_MODE="track_mixed_euclid_learned" \
PATH_BETA="${PATH_BETA:-0.95}" \
PATH_LEARNED_PATH_MIX="${PATH_LEARNED_PATH_MIX:-0.4}" \
FLOW_LEARNED_PATH_MIX="${FLOW_LEARNED_PATH_MIX:-0.4}" \
PATH_RHO_CONSTANT="0.5" \
PATH_GLOBAL_BATCH_SIZE="140" \
PATH_PER_GPU_BATCH_SIZE="70" \
FLOW_GLOBAL_BATCH_SIZE="768" \
FLOW_PER_GPU_BATCH_SIZE="384" \
PATH_STAGE_STEPS="${PATH_STAGE_STEPS:-3000}" \
PATH_LR_ANNEAL_STEPS="${PATH_LR_ANNEAL_STEPS:-3000}" \
PATH_CKPT_EVERY="${PATH_CKPT_EVERY:-3000}" \
PATH_EVAL_EVERY="${PATH_EVAL_EVERY:-3000}" \
PATH_AUTOSAVE_EVERY="${PATH_AUTOSAVE_EVERY:-200}" \
FLOW_STAGE_STEPS="${FLOW_STAGE_STEPS:-4000}" \
FLOW_CKPT_EVERY="${FLOW_CKPT_EVERY:-2000}" \
FLOW_AUTOSAVE_EVERY="${FLOW_AUTOSAVE_EVERY:-200}" \
FLOW_SAVED_EMA_LIST="0.999" \
FLOW_CHAIN_EMA_LABEL="ema0.999" \
MG_START_STEP="${MG_START_STEP:-0}" \
MG_DATA_RATIO_BASE="${MG_DATA_RATIO_BASE:-0.2}" \
MG_DROP_FRAC="${MG_DROP_FRAC:-0.1}" \
MG_W_LO="${MG_W_LO:-1.45}" \
MG_W_HI="${MG_W_HI:-1.45}" \
MG_DATA_SIDE_THRESHOLD="${MG_DATA_SIDE_THRESHOLD:-0.75}" \
MG_CLASS_DROPOUT_PROB="${MG_CLASS_DROPOUT_PROB:-0.0}" \
MG_LEARN_SIGMA="${MG_LEARN_SIGMA:-0}" \
sbatch "$LAUNCHER"
